#!/usr/bin/perl
use warnings;
use strict;
use List::Util qw( shuffle );
die "program num max" unless (scalar(@ARGV) == 1);
my ($num) = @ARGV;
print "@{[ shuffle 1 .. $num ]}\n";

for (my $i = 0; $i < $num; $i++) {
		#print (int rand($max));
		#print "@{[ shuffle 1 .. 20 ]}\n" for 1 .. 5;
		#print (" ");
}
